# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb6ab5f9dc8b21747fe59b236e8e3cb1360361d577b25ce58997bcc53df5382b69531b1f6e0a43f2150a9d6ea1496f193990784e35c69b85eb389300895eb715

test:
  secret_key_base: cff9cabaa6c5ea47329787b84120c780b01e6e55509ebe34762c9e65264cd652ff7b64ca4aec42cfd935606092d811860ed90da75f29c73f7884a768b5c7b91a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
